---
# LAN Tasks Configuration for UCSM
# Common variables that customers need to update are defined under group_vars/all.yml
# Not so common Variables (VLAN assignement etc, policies etc.) can be modified under ../defaults/main.yml
#
#Configure Management IP Pool
- include_tasks: configure_ucs_mgmt_ip_pool.yml
# Configure VLANs in UCS
- include_tasks: configure_ucs_vlans.yml
# Configure UCS MAC Pools A and B
- include_tasks: configure_ucs_mac_pools.yml
# Configure Network Control Policies to enable CDP and LLDP
- include_tasks: configure_ucs_NCP.yml
# VMware Adapter Policy for High Traffic
- include_tasks: configure_ucs_adapter_policy.yml
# # Configure vNIC Templates
- include_tasks: configure_ucs_vnic_templates.yml
# Configure LAN Connectivity Policy
- include_tasks: configure_ucs_LCP.yml
