---
# Server Tasks Configuration for UCSM
# 
# Common variables that customers need to update can be foud in group_vars/all.yml
# Not so common Variables should be modified under ../default/main.yml
#
  # UUID Pool Configuration
  - include_tasks: configure_ucs_uuid_pool.yml

  # Server Pool Configuration for UCSM to add Rack servers
  - include_tasks: configure_ucs_server_pool.yml

  # Power Control Policy (PCP) - remove any power caps
  - include_tasks: configure_ucs_PCP.yml

  # Update Default Maintenance Policy  - Add user ACK for Reboot
  # and apply pending changes: On Next Reboot
  - include_tasks: update_ucs_maintenance_policy.yml

  # Local Disk Policy - Ignore Disks
  - include_tasks: configure_ucs_disk_policy.yml

  # Create BIOS Policy and update various settings
  - include_tasks: configure_ucs_bios_policy.yml

  # Configure Boot Policy to boot ESXi from local disk
  - include_tasks: configure_ucs_boot_policy.yml

  # Configure Service Profile Templates
  - include_tasks: configure_ucs_SPT.yml
